services:
  flask-app:
    build: .
    container_name: new_operator_
    ports:
      - "5002:5002"
    restart: always
    env_file:
      - .env
    environment:
      FLASK_ENV: production
      DB_PORT: 3306